name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Lint Check (Optional)
        run: |
          npm install eslint
          npx eslint . || echo "Lint issues found (but not failing build)"

      - name: Run Tests (if added)
        run: |
          echo "No tests yet. Add Jest or Mocha to run real tests."
